version: '2'

services:
  web:
    build:
      context: .
      dockerfile: ./DockerFile
    ports:
      - 8000:8000
    networks:
      - twitter-clone
    env_file: docker.env
    depends_on:
      - db

  db:
    image: library/postgres:11.3-alpine
    restart: unless-stopped
    ports:
      - 10000:5432
    networks:
      - twitter-clone
    environment:
      - POSTGRES_USER=twitter
      - POSTGRES_PASSWORD=twitter

networks:
  twitter-clone:
    driver: bridge
